# Cell 1 – Import Libraries

In [1]:
import sqlite3
import pandas as pd

# Cell 2 – Connect to Database

In [2]:
conn = sqlite3.connect("../db/nifty100.db")

print("Connected Successfully")

Connected Successfully

# Cell 3 – Show All Tables

In [3]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table'
ORDER BY name;
"""

pd.read_sql(query, conn)

                name
0           analysis
1       balancesheet
2           cashflow
3          companies
4          documents
5   financial_ratios
6        peer_groups
7      profitandloss
8        prosandcons
9            sectors
10      stock_prices

# Cell 4 – Total Companies

In [4]:
query = """
SELECT COUNT(*) AS Total_Companies
FROM companies;
"""

pd.read_sql(query, conn)

   Total_Companies
0                0

# Cell 5 – Row Counts

In [5]:
tables = [
    "companies",
    "profitandloss",
    "balancesheet",
    "cashflow",
    "stock_prices"
]

for table in tables:
    query = f"SELECT COUNT(*) AS Rows FROM {table};"
    df = pd.read_sql(query, conn)
    print(f"{table:20} {df.iloc[0,0]}")

companies            0
profitandloss        0
balancesheet         0
cashflow             0
stock_prices         0

# Cell 6 – Top 10 Companies

In [6]:
query = """
SELECT id,
       company_name,
       ticker
FROM companies
LIMIT 10;
"""

pd.read_sql(query, conn)

Empty DataFrame
Columns: [id, company_name, ticker]
Index: []

# Cell 7 – Profit & Loss Sample

In [7]:
query = """
SELECT *
FROM profitandloss
LIMIT 10;
"""

pd.read_sql(query, conn)

Empty DataFrame
Columns: [id, company_id, year, sales, expenses, operating_profit, opm_percentage, other_income, interest, depreciation, profit_before_tax, tax, net_profit, eps, dividend]
Index: []

# Cell 8 – Balance Sheet Sample

In [8]:
query = """
SELECT *
FROM balancesheet
LIMIT 10;
"""

pd.read_sql(query, conn)

Empty DataFrame
Columns: [id, company_id, year, equity_capital, reserves, borrowings, other_liabilities, cwip, total_liabilities, fixed_assets, investments, current_assets, other_asset, total_assets]
Index: []

# Cell 9 – Cash Flow Sample

In [9]:
query = """
SELECT *
FROM cashflow
LIMIT 10;
"""

pd.read_sql(query, conn)

Empty DataFrame
Columns: [id, company_id, year, operating_activity, investing_activity, financing_activity, net_cash_flow]
Index: []

# Cell 10 – Financial Ratios Sample

In [10]:
query = """
SELECT *
FROM financial_ratios
LIMIT 10;
"""

pd.read_sql(query, conn)

Empty DataFrame
Columns: [id, company_id, year, net_profit_margin_pct, operating_profit_margin_pct, return_on_equity_pct, debt_to_equity, interest_coverage, asset_turnover, free_cash_flow_cr, capex_cr, earnings_per_share, book_value_per_share, dividend_payout_ratio_pct, total_debt_cr, cash_from_operations_cr]
Index: []

# Cell 11 – Companies by Industry

In [11]:
query = """
SELECT
industry,
COUNT(*) AS Total
FROM companies
GROUP BY industry
ORDER BY Total DESC;
"""

pd.read_sql(query, conn)

Empty DataFrame
Columns: [industry, Total]
Index: []

# Cell 12 – Latest Financial Year

In [12]:
query = """
SELECT MAX(year) AS Latest_Year
FROM profitandloss;
"""

pd.read_sql(query, conn)

  Latest_Year
0        None

# Cell 13 – Foreign Key Check

In [13]:
query = """
PRAGMA foreign_key_check;
"""

pd.read_sql(query, conn)

Empty DataFrame
Columns: [table, rowid, parent, fkid]
Index: []

# Cell 14 – Database Summary

In [14]:
summary = {
    "Table": [],
    "Rows": []
}

tables = [
    "companies",
    "profitandloss",
    "balancesheet",
    "cashflow",
    "analysis",
    "documents",
    "prosandcons",
    "sectors",
    "financial_ratios",
    "peer_groups",
    "stock_prices"
]

for table in tables:
    count = pd.read_sql(
        f"SELECT COUNT(*) AS c FROM {table}",
        conn
    ).iloc[0,0]

    summary["Table"].append(table)
    summary["Rows"].append(count)

pd.DataFrame(summary)

               Table  Rows
0          companies     0
1      profitandloss     0
2       balancesheet     0
3           cashflow     0
4           analysis     0
5          documents     0
6        prosandcons     0
7            sectors     0
8   financial_ratios     0
9        peer_groups     0
10      stock_prices     0

# Cell 15 – Close Connection

In [15]:
conn.close()

print("Database Closed")

Database Closed